### ISSUE TITLE
3.0.11 fails to build: No such file or directory: 'LICENSE.rst'

### ISSUE THREAD

**Issue by yurivict** [tox-dev/filelock#53]
```
===>  Configuring for py27-filelock-3.0.11
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 42, in <module>
    license_ = open("LICENSE.rst").read()
IOError: [Errno 2] No such file or directory: 'LICENSE.rst'
*** Error code 1
```

FreeBSD, python-27, tarball from the PyPI site.

**Comment by koobs** [comment]
@yurivict This appears fixed in https://github.com/benediktschmitt/py-filelock/commit/b30bdc4fb998f5f4350257235eb51147f9e81862 

Can you patch setup.py, test and commit? Approved by: portmgr (portmgr: just fix it)

**Comment by cas--** [comment]
This is a duplicate of #52 and should be closed. Also 3.0.11 was pulled from Pypi so surprising could still get it...
